# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['bubblegum_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('bubblegum.html', '.'),
        ('bubblegum.ico', '.'),
    ],
    hiddenimports=[
        # Selenium core
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.edge',
        'selenium.webdriver.edge.webdriver',
        'selenium.webdriver.edge.options',
        'selenium.webdriver.edge.service',
        'selenium.webdriver.remote',
        'selenium.webdriver.remote.webdriver',
        'selenium.webdriver.remote.command',
        'selenium.webdriver.remote.errorhandler',
        'selenium.webdriver.remote.webelement',
        'selenium.webdriver.remote.remote_connection',
        'selenium.webdriver.chromium',
        'selenium.webdriver.chromium.webdriver',
        'selenium.webdriver.chromium.options',
        'selenium.webdriver.chromium.service',
        'selenium.webdriver.chromium.remote_connection',
        # Selenium common
        'selenium.webdriver.common',
        'selenium.webdriver.common.by',
        'selenium.webdriver.common.keys',
        'selenium.webdriver.common.action_chains',
        'selenium.webdriver.common.options',
        'selenium.webdriver.common.service',
        'selenium.webdriver.common.driver_finder',
        'selenium.webdriver.support',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.support.select',
        # Dependencies
        'certifi',
        'websocket',
        'websocket._core',
        'websocket._abnf',
        'websocket._url',
        'websocket._http',
        'websocket._socket',
        'websocket._exceptions',
        'websocket._logging',
        'websocket._cookiejar',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='BubbleGum',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='bubblegum.ico',
)
